site_name: Terraform Quest

theme:
  name: material
  palette:
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo
    #scheme: slate
    #toggle:
    # icon: material/brightness-4
    # name: Switch to light mode
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    #- navigation.footer
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.highlight

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/akashvarshney


